config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :blog_posts

  get 'your_posts' => 'blog_posts#your_posts'
  
  get 'user_posts' => 'blog_posts#user_posts'
  

  get 'users/index'  => 'blog_posts#index'
  
  get 'index'  => 'blog_posts#index'
  
  get 'blog_posts/index'  => 'blog_posts#index'

  get 'ilovetocode'  => 'blog_posts#index'

  get 'users/about' => 'blog_posts#about'

  get 'blog_posts/about' => 'blog_posts#about'

  get 'users/contact' => 'blog_posts#contact'
   
  get 'about' => 'blog_posts#about'

  get 'contact' => 'blog_posts#contact'
   
  get 'show' => 'blog_posts#show'
   
   get 'edit' => 'blog_posts#edit'
   
get 'sign_up' => 'devise#new'
   
   get 'new' => 'blog_posts#new'
  root 'blog_posts#index'

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    
end

app/models/comment.rb
class Comment < ActiveRecord::Base


    belongs_to :blog_post 
    belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
         
  has_many :blog_posts
  has_many :comments
  
  
  #   validate :password_complexity

  # def password_complexity
  #   if password.present? and not password.match(/^(?=.*[a-z])(?=.*[A-Z])(?=.*\d). /)
  #     errors.add :password, "must include at least one lowercase letter, one uppercase letter, and one digit"
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :authenticate_user!
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, 
    :password_confirmation, :name, :username, :birthday) }

   devise_parameter_sanitizer.for(:account_update) { |u| u.permit({ roles: [] }, :email, :password, 
   :password_confirmation, :current_password, :name, :username, :birthday) }
  end
  
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
    @comment =Comment.new
  end

  def user_posts
    @user = User.find(params[:id])
  end

  def your_posts

  end
    
    
  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment =Comment.new
    
  end
  
  def about
    # @blog_posts = BlogPost.all
    # @comment =Comment.new
    @color = params[:color]
  end

  def contact
    # @blog_posts = BlogPost.all
    # @comment =Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end

  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
    

  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "Title" %>
  </div>

  <div class="field">
    <p>Authored by: <%= current_user.username %> 
  </div>

   <div class="form-group cant-see-me">
    <%= f.number_field :user_id, value: current_user.id %>
    <%=f.text_field :author, value: current_user.username %>
  </div>
  
  
  <div class="field" >
    <%= f.text_area :blog_entry, class: "form-control", placeholder: "Type Blog Entry Here, Please", rows: 20 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_posts/about.html.erb
<p id="notice"><%= notice %></p>

<h1>About Mike's Blog</h1>

<p>Welcome <%= current_user.username %>!</p>

<p style= "color:<%=@color%>">This is the blog I built using ruby on rails at c9.io for the class I am taking at Tech Talent South - Dallas.  </p>
<p style= "color:<%=@color%>">I started this project on Monday, August 31, 2015, in the morning, worked on it a bit in the afternoon, and continued to work on it on Tuesday, September 1, 2015.  </p>

<p style= "color:<%=@color%>">The buttons below will change the color of the text on this page</p>



<p><%= link_to "Blue", "about?color=blue", class: "btn btn-primary" %><%= link_to "Purple", "about?color=purple", class: "btn btn-purple" %><%= link_to "Red", "about?color=red", class: "btn btn-red" %><%= link_to "Green", "about?color=green", class: "btn btn-green" %><%= link_to "Black", "about?color=black", class: "btn btn-black" %></p>

app/views/blog_posts/contact.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact Mike</h1>


<p>Welcome <%= current_user.username %>!</p>

<p>You can contact me in several ways.  I prefer being contacted by smoke signals, semaphore, and telegraph.  </p>





<audio controls>
	<source src="http://mattersofgrey.com/audio/jawa.mp3" type="audio/mpeg" />
	<a href="http://mattersofgrey.com/audio/jawa.mp3">jawa</a>
</audio>

<audio controls>
	<source src="http://mattersofgrey.com/audio/r2d2-squeaks3.mp3" type="audio/mpeg" />
	<a href="http://mattersofgrey.com/audio/r2d2-squeaks3.mp3">r2d2</a>
</audio>

<audio controls>
	<source src="http://kylesmyth.com/wp-content/uploads/2008/05/utinni.mp3" type="audio/mpeg" />
	<a href="http://kylesmyth.com/wp-content/uploads/2008/05/utinni.mp3">jawa2</a>
</audio>

<audio controls>
	<source src="http://www.moviewavs.com/0053148414/MP3S/Movies/Star_Wars/wookie2.mp3" type="audio/mpeg" />
	<a href="http://www.moviewavs.com/0053148414/MP3S/Movies/Star_Wars/wookie2.mp3">chewbacca</a>
</audio>

<audio controls>
	<source src="http://www.moviewavs.com/0053148414/MP3S/Movies/Star_Wars/starwars.mp3" type="audio/mpeg" />
	<a href="http://www.moviewavs.com/0053148414/MP3S/Movies/Star_Wars/starwars.mp3">main_theme</a>
</audio>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post, class:"btn btn-danger" %> 
<%= link_to 'Back', blog_posts_path , class:"btn btn-info"%>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mike's Blog</h1>
<% counter = 0 %>

<p>Welcome <%= current_user.username %>!</p>

  <div class= "row">
    <% @blog_posts.each do |blog_post| %>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">
              <%= link_to blog_post.title,  blog_post %>
          </div>
          <div class="panel-body">
            by: <%= blog_post.author %><br>
            <p><%= blog_post.blog_entry[0..250] %>...[ <%= link_to "READ MORE", blog_post %> ]
            <% blog_post.comments.each do |comment| %>
              <% counter +=1 %>
            <% end %>
            <% if counter >0 %>
              <%= link_to "[ #{counter} comments ]", blog_post_path(blog_post, :anchor => "comments") %>
              <% counter = 0 %>
            <% end %></p>
            <p><strong><%=blog_post.updated_at.strftime('%d %B %Y %H:%M:%S') %></strong></p>
          </div>
          
          <div class="panel-footer">

            <%= link_to 'Edit Blog Post', edit_blog_post_path(blog_post), class:"btn btn-warning" %>
            <%= link_to 'Destroy Post', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


<br>

<%= link_to 'New Blog post', new_blog_post_path, class: "btn btn-info" %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>


  <div class="panel panel-default">
          <div class="panel-heading">
            <p><strong>Title:</strong>
            <%= @blog_post.title %>
            </p>
            <p>
              <strong>Author:</strong>

              <%= link_to @blog_post.user.username, user_posts_path(id: @blog_post.user_id)  %>
            </p>
          </div>
          <div class="panel-body">
              <p>
                <strong>Blog entry:</strong>
                <pre><%= @blog_post.blog_entry %></pre>
              </p>
              <p><strong><%=@blog_post.updated_at.strftime('%d %B %Y %H:%M:%S') %></strong></p>

            <% if current_user.id == @blog_post.user.id %>
                 <%= link_to 'Edit Blog Post', edit_blog_post_path(@blog_post), class:"btn btn-warning"%> 
            <% end %>
             
              
         
              <div class="row-fluid">
              
                <%= render 'comments/form' %>    
                    
              </div>      
                 
                 <div id="comments"><strong>COMMENTS:   </div></strong>
                <div class="panel-footer">
                    <% @blog_post.comments.each do |comment| %>
                        <div class= "panel-body">
                        <p><strong><%= link_to comment.user.username, user_posts_path(id: comment.user.id) %></strong> said: </p>
                        <p>"<%= comment.comment_entry %>"</p>
                        <p>at: <strong><%=comment.updated_at.strftime('%d %B %Y %H:%M:%S') %></strong></p>
                        </div>
                    <% end %>
                </div>              
             </div>
 
  
  </div>




<%= link_to 'Back', blog_posts_path, class:"btn btn-info" %>

app/views/blog_posts/user_posts.html.erb
<h1><%=@user.username %>'s Page</h1>

<p><strong>Name:</strong> <%= @user.name %></p>

<p><strong>Birthday:</strong> <%= @user.birthday.strftime("%m/%d/%Y") %></p>

<div class="row">
      <% @user.blog_posts.each do |blog_post| %>
<div class="col-md-12">
  <div class="panel panel-success">
  <div class="panel-heading">
        <%= link_to blog_post.title, blog_post %>

    </div>
  <div class="panel-body">
  by <%= blog_post.user.username %>
        <p><span class='posted-at'>posted at: <%= blog_post.created_at.strftime('%m/%d/%Y at %I:%M%p')%></span></p>
    <p><%= blog_post.blog_entry[0..250] %>...[<%= link_to "Read More", blog_post%>] </p><br />
    </div>
    <% if current_user.id == blog_post.user.id %>
        <div class="panel-footer">
                
            <%= link_to 'Edit Blog Post', edit_blog_post_path(blog_post), class:"btn btn-warning" %>
            <%= link_to 'Destroy Post', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
                
        </div>
    <% end %>
  </div>

  </div>
    <% end %>

</div>

<br>

app/views/blog_posts/your_posts.html.erb
<p id="notice"><%= notice %></p>

<h1>Mike's Blog</h1>
<% counter = 0 %>

<p>Welcome <%= current_user.username %>!</p>
<p>These are your posts:</p>

  <div class= "row">
    <% current_user.blog_posts.each do |blog_post| %>
      <div class="col-md-12">
        <div class="panel panel-default">
          <div class="panel-heading">
              <%= link_to blog_post.title,  blog_post %>
          </div>
          <div class="panel-body">
            by: <%= blog_post.user.username %> <br>
            <p><%= blog_post.blog_entry[0..250] %>...[ <%= link_to "READ MORE", blog_post %> ]
            <% blog_post.comments.each do |comment| %>
              <% counter +=1 %>
            <% end %>
            <% if counter >0 %>
              <%= link_to "[ #{counter} comments ]", blog_post_path(blog_post, :anchor => "comments") %>
              <% counter = 0 %>
            <% end %></p>
            <p><strong><%=blog_post.updated_at.strftime('%d %B %Y %H:%M:%S') %></strong></p>
          </div>
          
          <div class="panel-footer">

            <%= link_to 'Edit Blog Post', edit_blog_post_path(blog_post), class:"btn btn-warning" %>
            <% if current_user.username == blog_post.user.username %>
                <%= link_to 'Destroy Post', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>


<br>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

  
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_area :comment_entry, class: "form-control", placeholder: "Please Type Comment Here, Thank You!", rows: 4 %>
  </div>
  
    <div class="field">

    <p>comment authored by: <%= current_user.username %></p>
    <!--this gets displayed properly-->
   
    
  </div>
  
    <div class="field cant-see-me">
      
      <!--so why doesn't this work?-->
      
      <%=f.text_field :author, value: current_user.username, data: { confirm: 'Are you sure? #{current_user.username}' } %>
      
      <%= f.number_field :blog_post_id, value: @blog_post.id %>
      <%= f.number_field :user_id, value: current_user.id %>
  </div>
  
  
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<p><strong><%=@comment.updated_at %></strong></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
    <title>Mike's Blog</title>
    

    <link rel="shortcut icon" type="image/x-icon" href="assets/favicon.ico" />`

  
 
  
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet" integrity="sha256-MfvZlkHCEqatNoGiOXveE8FIwMzZg4W85qfrfIFBfYc= sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">
    <link rel="stylesheet" href="http://netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">
  
<link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  
     <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.2/js/bootstrap.min.js"></script>
  
    <meta name="viewport"
</head>
<body>
  
 

     	<nav class="navbar navbar-inverse">
    	  <div class="container-fluid">
    	    <!-- Brand and toggle get grouped for better mobile display -->
    	    <div class="navbar-header">
    	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    	        <span class="sr-only">Toggle navigation</span>
    	        <span class="icon-bar"></span>
    	        <span class="icon-bar"></span>
    	        <span class="icon-bar"></span>
    	      </button>

  <% if user_signed_in? %>  
    	      <%=  link_to "All Posts", index_path, class: "navbar-brand" %>
    	    </div>
    	
    	    <!-- Collect the nav links, forms, and other content for toggling -->
    	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    	      <ul class="nav navbar-nav">
    	        <li><%= link_to "Your Posts", your_posts_path %></li>
    	        <li><%= link_to "About", about_path %> </li>
    	        <li><%= link_to "Contact Us", contact_path %> </li>
    	        <li><%= link_to 'New Blog post', new_blog_post_path %></li>
    	      </ul>
    	      <form class="navbar-form navbar-left" role="search">
    	        <div class="form-group">
    	          <input type="text" class="form-control" placeholder="Search">
    	        </div>
    	        <button type="submit" class="btn btn-default">Search the site</button>
    	      </form>
    	      <ul class="nav navbar-nav navbar-right">
    	        
    	          <li><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %></li>
    	          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %></li>
    	       
    	       </ul>
    	        
    	 <% else %>
    	   <div class="navbar-brand">
    	   <%= link_to "Sign Up", new_user_registration_path %>
    	    </div>  
    	 <% end %> 
    	    </div><!-- /.navbar-collapse -->
    	  </div><!-- /.container-fluid -->
    	</nav>

 
  <div class='container'>

 
      <%= yield %>
      
    </div>
  


</body>
</html>